### ISSUE TITLE
Import failed

### ISSUE THREAD

**Issue by romasorin** [tianlang0704/ComfyUI-StableProjectorzBridge#2]
After installing in comfyUI node downloader - everytime i have this bug 
0.0 seconds (IMPORT FAILED): F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-StableProjectorzBridge

Comfy is latest version, also trying to download and import manually - same problem
0.0 seconds (IMPORT FAILED): F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-StableProjectorzBridge-master

**Comment by tianlang0704** [comment]
The actual error is shown earlier than these two lines, could you post full log or as much as you could, so I can pinpoint the error with your installation? Thanks.

**Comment by romasorin** [comment]
```
F:\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --lowvram --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-06-15 10:43:11.979630
** Platform: Windows
** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
** Python executable: F:\ComfyUI_windows_portable\python_embeded\python.exe
** Log path: F:\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   3.7 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 8188 MB, total RAM 16065 MB
xformers version: 0.0.25
Set vram state to: LOW_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Laptop GPU : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\lgm\core\attention.py:22: UserWarning: xFormers is available (Attention)
  warnings.warn("xFormers is available (Attention)")
### Loading: ComfyUI-Impact-Pack (V4.83.6)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.6)
### Loading: ComfyUI-Inspire-Pack (V0.67.1)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Manager (V2.38)
### ComfyUI Revision: 2072 [40e124c6] | Released on '2024-03-18'
ComfyUI Tutorial Nodes BK REMOVE: Loaded
Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-StableProjectorzBridge\__init__.py", line 3, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-StableProjectorzBridge\nodes.py", line 3, in <module>
    from tkinter import Image
ModuleNotFoundError: No module named 'tkinter'

Cannot import F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-StableProjectorzBridge module for custom nodes: No module named 'tkinter'
Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-StableProjectorzBridge-master\__init__.py", line 3, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-StableProjectorzBridge-master\nodes.py", line 3, in <module>
    from tkinter import Image
ModuleNotFoundError: No module named 'tkinter'

Cannot import F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-StableProjectorzBridge-master module for custom nodes: No module named 'tkinter'
(pysssss:WD14Tagger) [DEBUG] Available ORT providers: AzureExecutionProvider, CPUExecutionProvider
(pysssss:WD14Tagger) [DEBUG] Using ORT providers: CUDAExecutionProvider, CPUExecutionProvider
Workspace manager - Openning file hash dict
### Loading: Workspace Manager (V1.0.0)
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
[comfyui_controlnet_aux] | INFO -> Using ckpts path: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py:26: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\huggingface\\__init__.py'

Cannot import F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\huggingface module for custom nodes: [Errno 2] No such file or directory: 'F:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\huggingface\\__init__.py'
[custom_nodes.comfyui_controlnet_aux] | INFO -> Using ckpts path: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[custom_nodes.comfyui_controlnet_aux] | INFO -> Using symlinks: False
[custom_nodes.comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']

Import times for custom nodes:
   0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\kohya_hiresfix.py
   0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl_utility.py
   0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rembg-comfyui-node
   0.0 seconds (IMPORT FAILED): F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\huggingface
   0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\canvas_tab
   0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Lora-Training-in-Comfy
   0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Image-Captioning-in-ComfyUI
   0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl_prompt_styler
   0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Noise
   0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
   0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_kkTranslator_nodes
   0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds (IMPORT FAILED): F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-StableProjectorzBridge-master
   0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\tdxh_node_comfyui
   0.0 seconds (IMPORT FAILED): F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-StableProjectorzBridge
   0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-workspace-manager
   0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.1 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Remover
   0.1 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.4 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   1.2 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   5.3 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
```

**Comment by romasorin** [comment]
also `pip install tk` in cmd doesnt help

**Comment by tianlang0704** [comment]
> also `pip install tk` in cmd doesnt help

I fixed it, someone mentioned this tkinter error in standalone installation.
it was added by mistake, and I removed it in one file and missed this one.  Now it's all removed.
Please reinstall and see if it's fixed.
And thanks for letting me know. :D

**Comment by romasorin** [comment]
Yeah, it's work! Thank you for this node!
